# Application Name
spring.application.name=Banking

# Server Port
server.port=8090

# Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/banking-db
spring.datasource.username=root
spring.datasource.password=1234
spring.jpa.hibernate.ddl-auto=update
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JWT Secret Key (Replace 'your_secret_jwt_string' with an actual 32+ character key)
secreteJwtString=QAU21yVhYKc9wFH701SZB62ZYiVoBsjQBMJDrGyCkItpS2EhO5rePOsKX7t6QUtYbSpItocaBQK9Di45ThVqM8u



